/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appsalud;

import java.util.ArrayList;

/**
 *
 * @author garci
 */
public class ActividadGenerica extends javax.swing.JFrame {

    private Usuario usuario;
    private ArrayList<Usuario> listaUsuarios;
    /**
     * Creates new form ActividadGenerica
     */
    public ActividadGenerica(Usuario usuario, ArrayList<Usuario> listaUsuarios) {
        this.usuario = usuario;
        this.listaUsuarios = listaUsuarios;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblActividad = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        spinnerInicio = new javax.swing.JSpinner();
        lblFinal = new javax.swing.JLabel();
        spinnerFinal = new javax.swing.JSpinner();
        lblDistancia = new javax.swing.JLabel();
        spinnerDistancia = new javax.swing.JSpinner();
        lblFCMax = new javax.swing.JLabel();
        spinnerFCMax = new javax.swing.JSpinner();
        lblFCMin = new javax.swing.JLabel();
        spinnerFCMin = new javax.swing.JSpinner();
        btnRegistrar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblActividad.setFont(new java.awt.Font("Arial Nova Light", 0, 36)); // NOI18N
        lblActividad.setForeground(new java.awt.Color(255, 255, 255));
        lblActividad.setText("Estás registrando una actividad genérica");
        getContentPane().add(lblActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, 50));

        lblInicio.setFont(new java.awt.Font("Arial Nova Light", 0, 21)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblInicio.setText("Fecha y hora de inicio:");
        getContentPane().add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, 40));

        spinnerInicio.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        spinnerInicio.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_YEAR));
        getContentPane().add(spinnerInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 240, 40));

        lblFinal.setFont(new java.awt.Font("Arial Nova Light", 0, 21)); // NOI18N
        lblFinal.setForeground(new java.awt.Color(255, 255, 255));
        lblFinal.setText("Fecha y hora de final:");
        getContentPane().add(lblFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, 40));

        spinnerFinal.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        spinnerFinal.setModel(new javax.swing.SpinnerDateModel());
        getContentPane().add(spinnerFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 240, 40));

        lblDistancia.setFont(new java.awt.Font("Arial Nova Light", 0, 21)); // NOI18N
        lblDistancia.setForeground(new java.awt.Color(255, 255, 255));
        lblDistancia.setText("Distancia recorrida (Km):");
        getContentPane().add(lblDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, 40));

        spinnerDistancia.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        spinnerDistancia.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));
        getContentPane().add(spinnerDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 240, 40));

        lblFCMax.setFont(new java.awt.Font("Arial Nova Light", 0, 21)); // NOI18N
        lblFCMax.setForeground(new java.awt.Color(255, 255, 255));
        lblFCMax.setText("Frecuencia cardíaca máxima (ppm):");
        getContentPane().add(lblFCMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, 40));

        spinnerFCMax.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        spinnerFCMax.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(spinnerFCMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 240, 40));

        lblFCMin.setFont(new java.awt.Font("Arial Nova Light", 0, 21)); // NOI18N
        lblFCMin.setForeground(new java.awt.Color(255, 255, 255));
        lblFCMin.setText("Frecuencia cardíaca mínima (ppm):");
        getContentPane().add(lblFCMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, 40));

        spinnerFCMin.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        spinnerFCMin.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(spinnerFCMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 240, 40));

        btnRegistrar.setBackground(new java.awt.Color(153, 153, 255));
        btnRegistrar.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar actividad");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 500, 210, 60));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/infitnityFondo.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        ActividadGenerica generica = new ActividadGenerica(usuario, listaUsuarios);
        generica.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActividadGenerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActividadGenerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActividadGenerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActividadGenerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel lblActividad;
    private javax.swing.JLabel lblDistancia;
    private javax.swing.JLabel lblFCMax;
    private javax.swing.JLabel lblFCMin;
    private javax.swing.JLabel lblFinal;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JSpinner spinnerDistancia;
    private javax.swing.JSpinner spinnerFCMax;
    private javax.swing.JSpinner spinnerFCMin;
    private javax.swing.JSpinner spinnerFinal;
    private javax.swing.JSpinner spinnerInicio;
    // End of variables declaration//GEN-END:variables
}
