package appsalud;

import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author garci
 */
public class CyclingFrame extends javax.swing.JFrame {

    private Usuario usuario = Sesion.getUsuarioActual();
    private LocalDateTime fhInicio;
    private LocalDateTime fhFin;
    private float distancia;
    private int fcMax;
    private int fcMin;
    private float cadencia;
    
    /**
     * Creates new form CyclingFrame
     */
    public CyclingFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrar = new javax.swing.JButton();
        lblPasos = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        lblDistancia = new javax.swing.JLabel();
        lblFCMax = new javax.swing.JLabel();
        spinnerDistancia = new javax.swing.JSpinner();
        spinnerFCMax = new javax.swing.JSpinner();
        spinnerFCMin = new javax.swing.JSpinner();
        lblActividad = new javax.swing.JLabel();
        lblFCMin = new javax.swing.JLabel();
        spinnerCadencia = new javax.swing.JSpinner();
        lblFinal = new javax.swing.JLabel();
        spinnerFinal = new javax.swing.JSpinner();
        spinnerInicio = new javax.swing.JSpinner();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setBackground(new java.awt.Color(153, 153, 255));
        btnRegistrar.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setLabel("Registrar sesión de cycling");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 280, 60));

        lblPasos.setFont(new java.awt.Font("Arial Nova Light", 0, 20)); // NOI18N
        lblPasos.setForeground(new java.awt.Color(255, 255, 255));
        lblPasos.setText("Cadencia (Pedaladas por minuto):");
        getContentPane().add(lblPasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, 40));

        lblInicio.setFont(new java.awt.Font("Arial Nova Light", 0, 21)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblInicio.setText("Fecha y hora de inicio:");
        getContentPane().add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, 40));

        lblDistancia.setFont(new java.awt.Font("Arial Nova Light", 0, 21)); // NOI18N
        lblDistancia.setForeground(new java.awt.Color(255, 255, 255));
        lblDistancia.setText("Distancia recorrida (Km):");
        getContentPane().add(lblDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, 40));

        lblFCMax.setFont(new java.awt.Font("Arial Nova Light", 0, 19)); // NOI18N
        lblFCMax.setForeground(new java.awt.Color(255, 255, 255));
        lblFCMax.setText("Frecuencia cardíaca máxima (ppm):");
        getContentPane().add(lblFCMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, 40));

        spinnerDistancia.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        spinnerDistancia.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));
        getContentPane().add(spinnerDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 290, 40));

        spinnerFCMax.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        spinnerFCMax.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(spinnerFCMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 290, 40));

        spinnerFCMin.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        spinnerFCMin.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(spinnerFCMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 290, 40));

        lblActividad.setFont(new java.awt.Font("Arial Nova Light", 0, 36)); // NOI18N
        lblActividad.setForeground(new java.awt.Color(255, 255, 255));
        lblActividad.setText("Estás registrando una sesión de cycling");
        getContentPane().add(lblActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, 50));

        lblFCMin.setFont(new java.awt.Font("Arial Nova Light", 0, 19)); // NOI18N
        lblFCMin.setForeground(new java.awt.Color(255, 255, 255));
        lblFCMin.setText("Frecuencia cardíaca mínima (ppm):");
        getContentPane().add(lblFCMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, 40));

        spinnerCadencia.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        spinnerCadencia.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        getContentPane().add(spinnerCadencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 290, 40));

        lblFinal.setFont(new java.awt.Font("Arial Nova Light", 0, 21)); // NOI18N
        lblFinal.setForeground(new java.awt.Color(255, 255, 255));
        lblFinal.setText("Fecha y hora de final:");
        getContentPane().add(lblFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, 40));

        spinnerFinal.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        spinnerFinal.setModel(new javax.swing.SpinnerDateModel());
        getContentPane().add(spinnerFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 290, 40));

        spinnerInicio.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        spinnerInicio.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_YEAR));
        getContentPane().add(spinnerInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 290, 40));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/infitnityFondo.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        //Recoger inputs
        Date dateInicio = (Date) spinnerInicio.getValue();
        fhInicio = dateInicio.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
        Date dateFin = (Date) spinnerFinal.getValue();
        fhFin = dateFin.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
        distancia = (float) spinnerDistancia.getValue();
        fcMax = (int) spinnerFCMax.getValue();
        fcMin = (int) spinnerFCMin.getValue();
        cadencia = (int) spinnerCadencia.getValue();
       
        //Comprobar que los datos introducidos son válidos
        if (Cycling.actividadValida(fhInicio, fhFin, distancia, fcMin, fcMax, cadencia)){ 
            
            // Crear actividad
            Cycling cycling = new Cycling(fhInicio, fhFin, distancia, fcMax, fcMin, cadencia); 
            
            //Mostrar mensaje de actividad creada con éxito
            JOptionPane.showMessageDialog(null, "Actividad creada con éxito.", "", JOptionPane.INFORMATION_MESSAGE);
            
            //Añadir actividad al historial del usuario
            usuario.getHistorialActividades().add(cycling);
            
            //Serializar
            UsuariosManager manager = UsuariosManager.getInstance();
            manager.guardarUsuarios();
            
            //Volver al menú principal
            MenuPrincipal menu = new MenuPrincipal();
            menu.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CyclingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CyclingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CyclingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CyclingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel lblActividad;
    private javax.swing.JLabel lblDistancia;
    private javax.swing.JLabel lblFCMax;
    private javax.swing.JLabel lblFCMin;
    private javax.swing.JLabel lblFinal;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblPasos;
    private javax.swing.JSpinner spinnerCadencia;
    private javax.swing.JSpinner spinnerDistancia;
    private javax.swing.JSpinner spinnerFCMax;
    private javax.swing.JSpinner spinnerFCMin;
    private javax.swing.JSpinner spinnerFinal;
    private javax.swing.JSpinner spinnerInicio;
    // End of variables declaration//GEN-END:variables
}
