package appsalud;

import java.io.*;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;



public class GoPremium extends javax.swing.JFrame {
    
    private Usuario usuario;
    private ArrayList<Usuario> listaUsuarios;
    private static int tipoSusc;
    private static String oldPass; 
    private static String newPass; 
    private static String newPassConf; 
    
    /**
     * Creates new form GoPremium
     */
    public GoPremium(Usuario usuario, ArrayList<Usuario> listaUsuarios) {
        this.usuario = usuario;
        this.listaUsuarios = listaUsuarios;
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPremium = new javax.swing.JLabel();
        lblEligeDuracion = new javax.swing.JLabel();
        cboxTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblOldPass = new javax.swing.JLabel();
        pwdOld = new javax.swing.JPasswordField();
        lblNewPass1 = new javax.swing.JLabel();
        pwdNew1 = new javax.swing.JPasswordField();
        lblNewPass2 = new javax.swing.JLabel();
        pwdNew2 = new javax.swing.JPasswordField();
        btnGoPremium = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPremium.setFont(new java.awt.Font("Arial Nova Light", 0, 48)); // NOI18N
        lblPremium.setForeground(new java.awt.Color(255, 255, 255));
        lblPremium.setText("Hazte premium");
        getContentPane().add(lblPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, 100));

        lblEligeDuracion.setFont(new java.awt.Font("Arial Nova Light", 0, 20)); // NOI18N
        lblEligeDuracion.setForeground(new java.awt.Color(255, 255, 255));
        lblEligeDuracion.setText("Elige la duración de tu suscripción:");
        getContentPane().add(lblEligeDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 300, 30));

        cboxTipo.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        cboxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mensual", "Anual", "Indefinida" }));
        getContentPane().add(cboxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 160, 30));

        jLabel2.setFont(new java.awt.Font("Arial Nova Light", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Debemos reforzar la seguridad de tu cuenta.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 380, 30));

        jLabel3.setFont(new java.awt.Font("Arial Nova Light", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Crea una nueva contraseña que contenga más de 8 caracteres, un número, una mayúscula y un caracter especial.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 730, 30));

        lblOldPass.setFont(new java.awt.Font("Arial Nova Light", 0, 20)); // NOI18N
        lblOldPass.setForeground(new java.awt.Color(255, 255, 255));
        lblOldPass.setText("Primero debes introducir tu anterior contraseña");
        getContentPane().add(lblOldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 400, -1));
        getContentPane().add(pwdOld, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 400, 30));

        lblNewPass1.setFont(new java.awt.Font("Arial Nova Light", 0, 20)); // NOI18N
        lblNewPass1.setForeground(new java.awt.Color(255, 255, 255));
        lblNewPass1.setText("Establece aquí tu nueva contraseña");
        getContentPane().add(lblNewPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 310, -1));
        getContentPane().add(pwdNew1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 400, 30));

        lblNewPass2.setFont(new java.awt.Font("Arial Nova Light", 0, 20)); // NOI18N
        lblNewPass2.setForeground(new java.awt.Color(255, 255, 255));
        lblNewPass2.setText("Confirma aquí tu nueva contraseña");
        getContentPane().add(lblNewPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 300, -1));
        getContentPane().add(pwdNew2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 400, 30));

        btnGoPremium.setBackground(new java.awt.Color(153, 153, 255));
        btnGoPremium.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        btnGoPremium.setForeground(new java.awt.Color(255, 255, 255));
        btnGoPremium.setText("Hacerme premium");
        btnGoPremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoPremiumActionPerformed(evt);
            }
        });
        getContentPane().add(btnGoPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 210, 60));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/infitnityFondo.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoPremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoPremiumActionPerformed
        
        tipoSusc = cboxTipo.getSelectedIndex();
        oldPass = pwdOld.getText();
        newPass = pwdNew1.getText();
        newPassConf = pwdNew2.getText();
        
        if(!newPass.equalsIgnoreCase(newPassConf)){ //Las contraseñas nuevas no coinciden.
            JOptionPane.showMessageDialog(null, "La contraseña debe coincidir con la confirmación.","Error pasando a premium.",JOptionPane.ERROR_MESSAGE); 
        }else if(!UsuarioPremium.validarPasswordPremium(newPass)){ //La nueva contraseña no es segura.
            JOptionPane.showMessageDialog(null, "La contraseña debe cumplir los requisitos de seguridad.","Error pasando a premium.",JOptionPane.ERROR_MESSAGE); 
        } else if(!oldPass.equalsIgnoreCase(usuario.getPassword())){ //La contraseña anterior es incorrecta
            JOptionPane.showMessageDialog(null, "La contraseña es incorrecta.","Error pasando a premium.",JOptionPane.ERROR_MESSAGE); 
        }else{ //Todo correcto, creamos cuenta premium.
            //Crear cuenta con nueva contraseña
            usuario.setPassword(newPassConf);
            UsuarioPremium usuarioPremium = new UsuarioPremium(usuario, tipoSusc, LocalDate.now());
            //Guardar Usuario premium
            // 1. Cargar lista existente
            ArrayList<UsuarioPremium> listaUsuariosP = UsuariosManager.cargarUsuariosPremium();
            // 2. Añadir nuevo usuario
            listaUsuariosP.add(usuarioPremium);
            // 3. Guardar lista actualizada
            UsuariosManager.guardarUsuariosPremium(listaUsuariosP);
            // 4. Actualizar contraseña del fichero de usuarios general
            // 4.1. Actualizamos en la lista de usuarios
            for(Usuario u : listaUsuarios){
                if(u.getUsername().equalsIgnoreCase(usuario.getUsername())){
                    usuario.setPassword(newPassConf);
                }
            }
            // 4.2. Serializamos la lista modificada
            UsuariosManager.guardarUsuarios(listaUsuarios);
            // 5. Mostrar mensaje de éxito
            JOptionPane.showMessageDialog(null, "Cuenta creada con éxito.", "", JOptionPane.INFORMATION_MESSAGE);
            // 6. Volver al menú principal
            MenuPrincipal menuPrincipal = new MenuPrincipal(usuario, listaUsuarios);
            menuPrincipal.setVisible(true);
            this.dispose();
        }
        
        
    }//GEN-LAST:event_btnGoPremiumActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GoPremium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GoPremium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GoPremium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GoPremium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoPremium;
    private javax.swing.JComboBox<String> cboxTipo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblEligeDuracion;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNewPass1;
    private javax.swing.JLabel lblNewPass2;
    private javax.swing.JLabel lblOldPass;
    private javax.swing.JLabel lblPremium;
    private javax.swing.JPasswordField pwdNew1;
    private javax.swing.JPasswordField pwdNew2;
    private javax.swing.JPasswordField pwdOld;
    // End of variables declaration//GEN-END:variables
}
