/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appsalud;

/**
 *
 * @author garci
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMenu = new javax.swing.JLabel();
        lblIMC = new javax.swing.JLabel();
        btnGoPremium = new javax.swing.JButton();
        btnCambiarContraseña = new javax.swing.JButton();
        btnInforme = new javax.swing.JButton();
        btnPeso = new javax.swing.JButton();
        btnActividad = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenu.setFont(new java.awt.Font("Arial Nova Light", 0, 48)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblMenu.setText("¿Qué quieres hacer hoy?");
        getContentPane().add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, 100));

        lblIMC.setFont(new java.awt.Font("Arial Nova Light", 0, 24)); // NOI18N
        lblIMC.setForeground(new java.awt.Color(255, 255, 255));
        lblIMC.setText("IMC:");
        getContentPane().add(lblIMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 360, 40));

        btnGoPremium.setBackground(new java.awt.Color(255, 204, 255));
        btnGoPremium.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        btnGoPremium.setForeground(new java.awt.Color(102, 102, 102));
        btnGoPremium.setText("Hacerme premium");
        btnGoPremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoPremiumActionPerformed(evt);
            }
        });
        getContentPane().add(btnGoPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 210, 60));

        btnCambiarContraseña.setBackground(new java.awt.Color(255, 204, 255));
        btnCambiarContraseña.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        btnCambiarContraseña.setForeground(new java.awt.Color(102, 102, 102));
        btnCambiarContraseña.setText("Cambiar contraseña");
        btnCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCambiarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 210, 60));

        btnInforme.setBackground(new java.awt.Color(153, 153, 255));
        btnInforme.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        btnInforme.setForeground(new java.awt.Color(255, 255, 255));
        btnInforme.setText("Mostrar informe");
        btnInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformeActionPerformed(evt);
            }
        });
        getContentPane().add(btnInforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 210, 60));

        btnPeso.setBackground(new java.awt.Color(153, 153, 255));
        btnPeso.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        btnPeso.setForeground(new java.awt.Color(255, 255, 255));
        btnPeso.setText("Registrar peso");
        btnPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 210, 60));

        btnActividad.setBackground(new java.awt.Color(153, 153, 255));
        btnActividad.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        btnActividad.setForeground(new java.awt.Color(255, 255, 255));
        btnActividad.setText("Registrar actividad");
        btnActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActividadActionPerformed(evt);
            }
        });
        getContentPane().add(btnActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 210, 60));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/infitnityFondo.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInformeActionPerformed

    private void btnPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesoActionPerformed

    private void btnActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActividadActionPerformed

    private void btnGoPremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoPremiumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoPremiumActionPerformed

    private void btnCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiarContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActividad;
    private javax.swing.JButton btnCambiarContraseña;
    private javax.swing.JButton btnGoPremium;
    private javax.swing.JButton btnInforme;
    private javax.swing.JButton btnPeso;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIMC;
    private javax.swing.JLabel lblMenu;
    // End of variables declaration//GEN-END:variables
}
