/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appsalud;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author garci
 */
public class MenuPrincipal extends javax.swing.JFrame {

    Usuario usuario = Sesion.getUsuarioActual();
    ArrayList<Usuario> listaUsuarios;
    ArrayList<UsuarioPremium> listaUsuariosPremium;

    
    /**
     * Creates new form MenuPrincipal
     */
     
    public MenuPrincipal() {
        initComponents();
        lblHola.setText("Hola, "+ usuario.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHola = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        btnCambiarContraseña = new javax.swing.JButton();
        btnGoPremium = new javax.swing.JButton();
        btnInforme = new javax.swing.JButton();
        btnPeso = new javax.swing.JButton();
        btnActividad = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHola.setFont(new java.awt.Font("Arial Nova Light", 0, 36)); // NOI18N
        lblHola.setForeground(new java.awt.Color(255, 255, 255));
        lblHola.setText("Hola");
        getContentPane().add(lblHola, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 40));

        lblMenu.setFont(new java.awt.Font("Arial Nova Light", 0, 36)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblMenu.setText("¿Qué quieres hacer hoy?");
        getContentPane().add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, 100));

        btnCambiarContraseña.setBackground(new java.awt.Color(255, 204, 255));
        btnCambiarContraseña.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        btnCambiarContraseña.setForeground(new java.awt.Color(102, 102, 102));
        btnCambiarContraseña.setText("Cambiar contraseña");
        btnCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCambiarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 210, 60));

        btnGoPremium.setBackground(new java.awt.Color(255, 204, 255));
        btnGoPremium.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        btnGoPremium.setForeground(new java.awt.Color(102, 102, 102));
        btnGoPremium.setText("Hacerme premium");
        btnGoPremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoPremiumActionPerformed(evt);
            }
        });
        getContentPane().add(btnGoPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 210, 60));

        btnInforme.setBackground(new java.awt.Color(153, 153, 255));
        btnInforme.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        btnInforme.setForeground(new java.awt.Color(255, 255, 255));
        btnInforme.setText("Mostrar informe");
        btnInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformeActionPerformed(evt);
            }
        });
        getContentPane().add(btnInforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 210, 60));

        btnPeso.setBackground(new java.awt.Color(153, 153, 255));
        btnPeso.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        btnPeso.setForeground(new java.awt.Color(255, 255, 255));
        btnPeso.setText("Registrar peso");
        btnPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 210, 60));

        btnActividad.setBackground(new java.awt.Color(153, 153, 255));
        btnActividad.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        btnActividad.setForeground(new java.awt.Color(255, 255, 255));
        btnActividad.setText("Registrar actividad");
        btnActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActividadActionPerformed(evt);
            }
        });
        getContentPane().add(btnActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 210, 60));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/infitnityFondo.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento que se ejecuta al pulsar el botón para mostrar el informe.
     * 
     * Crea una nueva ventana de MostrarInforme, la hace visible y cierra la ventana actual.
     * 
     * @param evt Evento que dispara la acción (pulsar botón).
     */
    private void btnInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeActionPerformed
        MostrarInforme informe = new MostrarInforme();
        informe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInformeActionPerformed

    /**
     * Evento que se ejecuta al pulsar el botón para registrar el peso.
     * 
     * Crea una nueva ventana de RegistroPeso, la muestra y cierra la ventana actual.
     * 
     * @param evt Evento que dispara la acción (pulsar botón).
     */
    private void btnPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesoActionPerformed
        RegistroPeso rPeso = new RegistroPeso();
        rPeso.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPesoActionPerformed

    /**
     * Evento que se ejecuta al pulsar el botón para registrar una nueva actividad.
     * 
     * Abre la ventana de RegistroActividad, la muestra y cierra la ventana actual.
     * 
     * @param evt Evento que dispara la acción (pulsar botón).
     */
    private void btnActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActividadActionPerformed
        RegistroActividad rActividad = new RegistroActividad();
        rActividad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnActividadActionPerformed
    
    /**
     * Evento que se ejecuta al pulsar el botón para cambiar la contraseña.
     * 
     * Abre la ventana de CambiarPass, la muestra y cierra la ventana actual.
     * 
     * @param evt Evento que dispara la acción (pulsar botón).
     */
    private void btnCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarContraseñaActionPerformed
        CambiarPass cambiarPass = new CambiarPass();
        cambiarPass.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCambiarContraseñaActionPerformed

    /**
     * Evento que se ejecuta al pulsar el botón para gestionar la suscripción premium.
     * 
     * - Si el usuario ya tiene una suscripción premium activa, muestra un mensaje informativo.
     * - Si el usuario tiene una suscripción caducada, pregunta si desea reactivarla y en función de la respuesta
     *   abre la ventana para reactivar o muestra un mensaje informando que ya no es premium.
     * - Si el usuario no tiene cuenta premium, abre la ventana para crear una cuenta premium.
     * 
     * @param evt Evento que dispara la acción (pulsar botón).
     */
    private void btnGoPremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoPremiumActionPerformed
        if(UsuariosManager.existeUsuarioPremium(usuario.getUsername())  && UsuariosManager.dameUsuarioPremium(usuario.getUsername()).esPremium()){ //El usuario ya tiene una suscripción premium activa
            JOptionPane.showMessageDialog(null, "Ya eres premium.", "", JOptionPane.INFORMATION_MESSAGE);
        }else if(!UsuariosManager.dameUsuarioPremium(usuario.getUsername()).esPremium() && UsuariosManager.existeUsuarioPremium(usuario.getUsername())){ //El usuario existe pero se ha caducado la suscripcion
            int opcion = JOptionPane.showConfirmDialog(null, "Tu suscripción premium ha caducado. ¿Quieres reactivarla?");
            if (opcion == JOptionPane.YES_OPTION){
                UsuariosManager.dameUsuarioPremium(usuario.getUsername()).renovarSuscripcion();
                JOptionPane.showMessageDialog(null, "Vuelves a ser premium.");
            } else if (opcion == JOptionPane.NO_OPTION){
                JOptionPane.showMessageDialog(null, "Ya no eres premium.");
            } 
        }else{ //El usuario no tiene cuenta premium
            GoPremium goPremium = new GoPremium();
            this.dispose();
            goPremium.setVisible(true);
        }
        
    }//GEN-LAST:event_btnGoPremiumActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActividad;
    private javax.swing.JButton btnCambiarContraseña;
    private javax.swing.JButton btnGoPremium;
    private javax.swing.JButton btnInforme;
    private javax.swing.JButton btnPeso;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblHola;
    private javax.swing.JLabel lblMenu;
    // End of variables declaration//GEN-END:variables
}
