/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appsalud;

import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author garci
 */
public class MostrarInforme extends javax.swing.JFrame {
    
    private static final ArrayList<String> SEXO = new ArrayList<>(List.of("Varón", "Hembra"));
    private static final ArrayList<String> FACTORACTIVIDAD = new ArrayList<>(List.of("Sedentarismo", "Actividad ligera (1 a 3 veces por semana)", 
    "Actividad moderada (3 a 5 veces por semana)", "Actividad intensa (6 o 7 veces por semana)", "Actividad extremadamente alta (Atleta profesional)"));


    Usuario usuario = Sesion.getUsuarioActual();
    /**
     * Creates new form MostrarInforme
     */
    public MostrarInforme() {
        initComponents();
        lbl1.setText("Informe de " + usuario.getUsername());
        lbl2.setText("Nombre y apellidos: " + usuario.getNombre() + " " + usuario.getApellidos());
        lbl3.setText("Password: " + "*".repeat(usuario.getPassword().length()));
        lbl4.setText("Fecha de nacimiento: " + usuario.getFechaNacimiento().toString() + "   Edad: " + usuario.getEdad());
        lbl5.setText("Sexo: " + SEXO.get(usuario.getSexo()) + "   Peso: " +  usuario.getPeso() + "   Altura: " + usuario.getAltura());
        lbl6.setText(usuario.getIMC(usuario.getPeso()) + "   Factor de actividad: " + FACTORACTIVIDAD.get(usuario.getFactorActividad()));
        cargarHistorialActividades();
    }
    
    private void cargarHistorialActividades() {
    Usuario usuario = Sesion.getUsuarioActual(); // o como tengas guardado el usuario logueado
    ArrayList<Actividad> actividades = usuario.getHistorialActividades(); // ajusta el getter si hace falta

    DefaultTableModel modelo = (DefaultTableModel) tableAct.getModel();
    modelo.setRowCount(0); // Limpiar la tabla

    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

    for (Actividad a : actividades) {
        String tipo = a.getClass().getSimpleName();
        String extra = "";

        if (a instanceof Running) {
            extra = "Pasos: " + ((Running) a).getPasosTotales();
        } else if (a instanceof Swimming) {
            extra = "Brazadas: " + ((Swimming) a).getNumLargos();
        } else if (a instanceof Cycling) {
            extra = "Cadencia: " + ((Cycling) a).getCadencia();
        }

        Object[] fila = {
            tipo,
            a.getFhInicio().format(dtf),
            a.getFhFin().format(dtf),
            a.getDuracion(),
            String.format("%.2f", a.getDistancia()),
            String.format("%.2f", a.getKcal()),
            a.getFcMax(),
            a.getFcMin(),
            extra
        };

        modelo.addRow(fila);
    }
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        scrollAct = new javax.swing.JScrollPane();
        tableAct = new javax.swing.JTable();
        lbl8 = new javax.swing.JLabel();
        scrollPeso = new javax.swing.JScrollPane();
        tablePeso = new javax.swing.JTable();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl1.setBackground(new java.awt.Color(51, 51, 255));
        lbl1.setFont(new java.awt.Font("Arial Nova Light", 0, 36)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setText("Informe de");
        getContentPane().add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 700, -1));

        lbl2.setBackground(new java.awt.Color(51, 51, 255));
        lbl2.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        lbl2.setText("Nombre y apellidos:");
        getContentPane().add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 700, -1));

        lbl3.setBackground(new java.awt.Color(51, 51, 255));
        lbl3.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        lbl3.setForeground(new java.awt.Color(255, 255, 255));
        lbl3.setText("Password:");
        getContentPane().add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 700, -1));

        lbl4.setBackground(new java.awt.Color(51, 51, 255));
        lbl4.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        lbl4.setForeground(new java.awt.Color(255, 255, 255));
        lbl4.setText("Fecha de nacimiento -            Edad -");
        getContentPane().add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 700, -1));

        lbl5.setBackground(new java.awt.Color(51, 51, 255));
        lbl5.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        lbl5.setForeground(new java.awt.Color(255, 255, 255));
        lbl5.setText("Sexo -         Peso -               Altura -");
        getContentPane().add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 700, -1));

        lbl6.setBackground(new java.awt.Color(51, 51, 255));
        lbl6.setFont(new java.awt.Font("Arial Nova Light", 0, 16)); // NOI18N
        lbl6.setForeground(new java.awt.Color(255, 255, 255));
        lbl6.setText("IMC actual - Factor actividad");
        getContentPane().add(lbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 700, -1));

        lbl7.setBackground(new java.awt.Color(51, 51, 255));
        lbl7.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        lbl7.setForeground(new java.awt.Color(255, 255, 255));
        lbl7.setText("Historial de actividades");
        getContentPane().add(lbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 700, -1));

        scrollAct.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        tableAct.setFont(new java.awt.Font("Arial Nova Light", 0, 12)); // NOI18N
        tableAct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tipo", "Fecha y hora de inicio", "Fecha y hora de fin", "Duración", "Distancia", "Kcal consumidas", "Frecuencia Cardíaca Mínima", "Frecuencia Cardíaca Media", "Frecuencia Cardíaca Máxima", "Ritmo", "Elevación", "Pasos totales", "Cadencia", "Número de largos", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableAct.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableAct.setCellSelectionEnabled(true);
        scrollAct.setViewportView(tableAct);

        getContentPane().add(scrollAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 700, 100));

        lbl8.setBackground(new java.awt.Color(51, 51, 255));
        lbl8.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        lbl8.setForeground(new java.awt.Color(255, 255, 255));
        lbl8.setText("Historial de pesos");
        getContentPane().add(lbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 700, -1));

        tablePeso.setFont(new java.awt.Font("Arial Nova Light", 0, 12)); // NOI18N
        tablePeso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPeso.setViewportView(tablePeso);

        getContentPane().add(scrollPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 700, 100));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/infitnityFondo.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarInforme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarInforme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarInforme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarInforme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarInforme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JScrollPane scrollAct;
    private javax.swing.JScrollPane scrollPeso;
    private javax.swing.JTable tableAct;
    private javax.swing.JTable tablePeso;
    // End of variables declaration//GEN-END:variables
}
