package appsalud;

import java.time.*;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 * JFrame para registrar un cambio de peso del usuario.
 * Permite introducir un peso en kilogramos y una fecha para dicho registro,
 * y añade el nuevo peso al historial del usuario actual.
 * 
 * @author 
 */
public class RegistroPeso extends javax.swing.JFrame {

	/**
     * Usuario actual en sesión que realizará el registro de peso.
     */
    private Usuario usuario = Sesion.getUsuarioActual();

    /**
     * Peso que se va a registrar.
     */
    private float pesoRegistrar;

    /**
     * Fecha del registro de peso.
     */
    private LocalDate fechaPR;

    /**
     * Constructor que inicializa la ventana de registro de peso.
     */
    public RegistroPeso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRPeso = new javax.swing.JLabel();
        lblRPeso2 = new javax.swing.JLabel();
        spinnerRPeso = new javax.swing.JSpinner();
        lblRPesoFecha = new javax.swing.JLabel();
        spinnerFecha = new javax.swing.JSpinner();
        btnPeso = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRPeso.setFont(new java.awt.Font("Arial Nova Light", 0, 48)); // NOI18N
        lblRPeso.setForeground(new java.awt.Color(255, 255, 255));
        lblRPeso.setText("Registra un cambio en tu peso");
        getContentPane().add(lblRPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, 100));

        lblRPeso2.setFont(new java.awt.Font("Arial Nova Light", 0, 24)); // NOI18N
        lblRPeso2.setForeground(new java.awt.Color(255, 255, 255));
        lblRPeso2.setText("Introduce aquí el peso en kilogramos:");
        getContentPane().add(lblRPeso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, 40));

        spinnerRPeso.setFont(new java.awt.Font("Arial Nova Light", 0, 24)); // NOI18N
        spinnerRPeso.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(30.0f), Float.valueOf(30.0f), Float.valueOf(300.0f), Float.valueOf(1.0f)));
        getContentPane().add(spinnerRPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 390, 50));

        lblRPesoFecha.setFont(new java.awt.Font("Arial Nova Light", 0, 24)); // NOI18N
        lblRPesoFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblRPesoFecha.setText("¿En qué fecha se produjo el cambio?");
        getContentPane().add(lblRPesoFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 390, -1));

        spinnerFecha.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        spinnerFecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(-1420070400000L), new java.util.Date(), java.util.Calendar.DAY_OF_YEAR));
        spinnerFecha.setEditor(new javax.swing.JSpinner.DateEditor(spinnerFecha, "dd/MM/yyyy"));
        getContentPane().add(spinnerFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 390, 50));

        btnPeso.setBackground(new java.awt.Color(153, 153, 255));
        btnPeso.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        btnPeso.setForeground(new java.awt.Color(255, 255, 255));
        btnPeso.setText("Registrar peso");
        btnPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 210, 60));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/infitnityFondo.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción realizada al pulsar el botón para registrar un peso.
     * Recoge el peso y la fecha desde los componentes UI, crea un objeto Peso,
     * lo añade al historial del usuario, guarda los cambios y vuelve al menú principal.
     *
     * @param evt Evento generado por la acción del botón.
     */
    private void btnPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesoActionPerformed
        //Obtener peso
        pesoRegistrar = (float) spinnerRPeso.getValue();
        //Obtener la fecha del spinner en tipo Date y pasarla a LocalDate
        Date date = (Date) spinnerFecha.getValue();
        Instant instant = date.toInstant();
        ZoneId zona = ZoneId.systemDefault();
        fechaPR = instant.atZone(zona).toLocalDate();
        //Crear objeto peso a partir de los datos obtenidos.
        String imc = usuario.getIMC(pesoRegistrar);
        Peso pesoNuevo = new Peso(fechaPR, pesoRegistrar, imc);
        //Añadir el peso al historial.
        usuario.registrarPeso(pesoNuevo);
        //Serializar cambios
        UsuariosManager manager = UsuariosManager.getInstance();
        manager.guardarUsuarios();
        //Mostrar mensaje y volver a cargar el menú principal
        JOptionPane.showMessageDialog(null, "El peso ha sido registrado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPeso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPeso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPeso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPeso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPeso;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblRPeso;
    private javax.swing.JLabel lblRPeso2;
    private javax.swing.JLabel lblRPesoFecha;
    private javax.swing.JSpinner spinnerFecha;
    private javax.swing.JSpinner spinnerRPeso;
    // End of variables declaration//GEN-END:variables
}
