package appsalud;

import javax.swing.JFrame;

/**
 * Ventana gráfica para seleccionar el tipo de actividad que el usuario desea registrar.
 * 
 * Muestra botones para abrir formularios específicos de diferentes tipos de actividades:
 * actividad genérica, running, cycling y swimming.
 * Al pulsar un botón se abre la ventana correspondiente y se cierra esta.
 * 
 * Esta clase extiende {@link javax.swing.JFrame}.
 * 
 * @author Mariola
 */
public class RegistroActividad extends javax.swing.JFrame {

	/**
    * Crea e inicializa la ventana RegistroActividad.
    */
    public RegistroActividad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblActividad = new javax.swing.JLabel();
        btnGenerica = new javax.swing.JButton();
        btnRunning = new javax.swing.JButton();
        btnCycling = new javax.swing.JButton();
        btnSwimming = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblActividad.setFont(new java.awt.Font("Arial Nova Light", 0, 36)); // NOI18N
        lblActividad.setForeground(new java.awt.Color(255, 255, 255));
        lblActividad.setText("¿Qué actividad quieres registrar?");
        getContentPane().add(lblActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, 100));

        btnGenerica.setBackground(new java.awt.Color(153, 153, 255));
        btnGenerica.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        btnGenerica.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerica.setText("Actividad genérica");
        btnGenerica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenericaActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerica, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 210, 60));

        btnRunning.setBackground(new java.awt.Color(153, 153, 255));
        btnRunning.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        btnRunning.setForeground(new java.awt.Color(255, 255, 255));
        btnRunning.setText("Running");
        btnRunning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunningActionPerformed(evt);
            }
        });
        getContentPane().add(btnRunning, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 210, 60));

        btnCycling.setBackground(new java.awt.Color(153, 153, 255));
        btnCycling.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        btnCycling.setForeground(new java.awt.Color(255, 255, 255));
        btnCycling.setText("Cycling");
        btnCycling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCyclingActionPerformed(evt);
            }
        });
        getContentPane().add(btnCycling, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 210, 60));

        btnSwimming.setBackground(new java.awt.Color(153, 153, 255));
        btnSwimming.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        btnSwimming.setForeground(new java.awt.Color(255, 255, 255));
        btnSwimming.setText("Swimming");
        btnSwimming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwimmingActionPerformed(evt);
            }
        });
        getContentPane().add(btnSwimming, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 210, 60));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/infitnityFondo.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción al pulsar el botón "Actividad genérica".
     * Abre la ventana para registrar una actividad genérica y cierra la ventana actual.
     * @param evt Evento generado por la acción del botón.
     */
    private void btnGenericaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenericaActionPerformed
        ActividadGenerica generica = new ActividadGenerica();
        generica.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGenericaActionPerformed

    /**
     * Acción al pulsar el botón "Running".
     * Abre la ventana de registro para una actividad de running y cierra esta ventana.
     * 
     * @param evt Evento generado por el clic del botón.
     */
    private void btnRunningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunningActionPerformed
        RunningFrame running = new RunningFrame();
        running.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRunningActionPerformed

    /**
     * Acción al pulsar el botón "Cycling".
     * Abre la ventana de registro para una actividad de ciclismo y cierra esta ventana.
     * 
     * @param evt Evento generado por el clic del botón.
     */
    private void btnCyclingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCyclingActionPerformed
        CyclingFrame cycling = new CyclingFrame();
        cycling.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCyclingActionPerformed

    /**
     * Acción al pulsar el botón "Swimming".
     * Abre la ventana de registro para una actividad de natación y cierra esta ventana.
     * 
     * @param evt Evento generado por el clic del botón.
     */
    private void btnSwimmingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwimmingActionPerformed
        SwimmingFrame swimming = new SwimmingFrame();
        swimming.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSwimmingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCycling;
    private javax.swing.JButton btnGenerica;
    private javax.swing.JButton btnRunning;
    private javax.swing.JButton btnSwimming;
    private javax.swing.JLabel lblActividad;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
