/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appsalud;

/**
 *
 * @author garci
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSU = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        passwordFieldSU = new javax.swing.JPasswordField();
        lblPasswordConf = new javax.swing.JLabel();
        passwordFieldSUConf = new javax.swing.JPasswordField();
        lblFechaPeso = new javax.swing.JLabel();
        spinnerNacimiento = new javax.swing.JSpinner();
        spinnerPeso = new javax.swing.JSpinner();
        spinnerAltura = new javax.swing.JSpinner();
        cboxSexo = new javax.swing.JComboBox<>();
        btnCrearCuenta = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblFactor = new javax.swing.JLabel();
        cboxFactor = new javax.swing.JComboBox<>();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSU.setFont(new java.awt.Font("Arial Nova Light", 0, 48)); // NOI18N
        lblSU.setForeground(new java.awt.Color(255, 255, 255));
        lblSU.setText("Es un placer tenerte");
        getContentPane().add(lblSU, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, 100));

        lblUsername.setFont(new java.awt.Font("Arial Nova Light", 0, 24)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Nombre de usuario");
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 290, -1));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 310, 40));

        lblPassword.setFont(new java.awt.Font("Arial Nova Light", 0, 24)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Contraseña");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 130, -1));
        getContentPane().add(passwordFieldSU, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 310, 40));

        lblPasswordConf.setFont(new java.awt.Font("Arial Nova Light", 0, 24)); // NOI18N
        lblPasswordConf.setForeground(new java.awt.Color(255, 255, 255));
        lblPasswordConf.setText("Contraseña (Confirmación)");
        getContentPane().add(lblPasswordConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 280, -1));
        getContentPane().add(passwordFieldSUConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 310, 40));

        lblFechaPeso.setFont(new java.awt.Font("Arial Nova Light", 0, 24)); // NOI18N
        lblFechaPeso.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaPeso.setText("Fecha de nacimiento     Peso (KG)       Altura (CM)        Sexo");
        getContentPane().add(lblFechaPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 700, -1));

        spinnerNacimiento.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        spinnerNacimiento.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1420066740000L), new java.util.Date(-1420070400000L), new java.util.Date(1420066740000L), java.util.Calendar.DAY_OF_YEAR));
        spinnerNacimiento.setEditor(new javax.swing.JSpinner.DateEditor(spinnerNacimiento, "dd/MM/yyyy"));
        getContentPane().add(spinnerNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 220, 40));

        spinnerPeso.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        spinnerPeso.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(30.0f), Float.valueOf(30.0f), Float.valueOf(250.0f), Float.valueOf(1.0f)));
        getContentPane().add(spinnerPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 120, 40));

        spinnerAltura.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        spinnerAltura.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(100.0f), Float.valueOf(100.0f), Float.valueOf(300.0f), Float.valueOf(1.0f)));
        getContentPane().add(spinnerAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 150, 40));

        cboxSexo.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        cboxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Varón", "Hembra" }));
        cboxSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxSexoActionPerformed(evt);
            }
        });
        getContentPane().add(cboxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 110, 40));

        btnCrearCuenta.setBackground(new java.awt.Color(153, 153, 255));
        btnCrearCuenta.setFont(new java.awt.Font("Arial Nova Light", 0, 24)); // NOI18N
        btnCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCuenta.setText("Crear Cuenta");
        btnCrearCuenta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCrearCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 220, 50));

        lblNombre.setFont(new java.awt.Font("Arial Nova Light", 0, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 310, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 310, 40));

        lblApellidos.setFont(new java.awt.Font("Arial Nova Light", 0, 24)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidos.setText("Apellidos");
        getContentPane().add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 310, -1));
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 310, 40));

        lblFactor.setFont(new java.awt.Font("Arial Nova Light", 0, 24)); // NOI18N
        lblFactor.setForeground(new java.awt.Color(255, 255, 255));
        lblFactor.setText("Nivel de actividad física diaria");
        getContentPane().add(lblFactor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 310, -1));

        cboxFactor.setFont(new java.awt.Font("Arial Nova Light", 0, 16)); // NOI18N
        cboxFactor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguna", "Ligera (1 a 3 veces por semana)", "Moderada (3 a 5 veces por semana)", "Intensa (6 a 7 veces por semana)", "Soy atleta profesional" }));
        getContentPane().add(cboxFactor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 310, 40));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/infitnityFondo.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void cboxSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxSexoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JComboBox<String> cboxFactor;
    private javax.swing.JComboBox<String> cboxSexo;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblFactor;
    private javax.swing.JLabel lblFechaPeso;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordConf;
    private javax.swing.JLabel lblSU;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField passwordFieldSU;
    private javax.swing.JPasswordField passwordFieldSUConf;
    private javax.swing.JSpinner spinnerAltura;
    private javax.swing.JSpinner spinnerNacimiento;
    private javax.swing.JSpinner spinnerPeso;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
