/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appsalud;

import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author garci
 */
public class SwimmingFrame extends javax.swing.JFrame {

    private Usuario usuario = Sesion.getUsuarioActual();
    private LocalDateTime fhInicio;
    private LocalDateTime fhFin;
    private float distancia;
    private int fcMax;
    private int fcMin;
    private int tipo;
    private int numLargos;
    
    /**
     * Creates new form SwimmingFrame
     */
    public SwimmingFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFCMax = new javax.swing.JLabel();
        lblDistancia = new javax.swing.JLabel();
        spinnerFCMax = new javax.swing.JSpinner();
        btnRegistrar = new javax.swing.JButton();
        lblPasos = new javax.swing.JLabel();
        spinnerFCMin = new javax.swing.JSpinner();
        spinnerDistancia = new javax.swing.JSpinner();
        lblActividad = new javax.swing.JLabel();
        lblFCMin = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        spinnerInicio = new javax.swing.JSpinner();
        lblElevacion = new javax.swing.JLabel();
        spinnerLargos = new javax.swing.JSpinner();
        lblFinal = new javax.swing.JLabel();
        spinnerFinal = new javax.swing.JSpinner();
        cboxTipo = new javax.swing.JComboBox<>();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFCMax.setFont(new java.awt.Font("Arial Nova Light", 0, 19)); // NOI18N
        lblFCMax.setForeground(new java.awt.Color(255, 255, 255));
        lblFCMax.setText("Frecuencia cardíaca máxima (ppm):");
        getContentPane().add(lblFCMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, 40));

        lblDistancia.setFont(new java.awt.Font("Arial Nova Light", 0, 21)); // NOI18N
        lblDistancia.setForeground(new java.awt.Color(255, 255, 255));
        lblDistancia.setText("Distancia recorrida (Km):");
        getContentPane().add(lblDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, 40));

        spinnerFCMax.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        spinnerFCMax.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(spinnerFCMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 300, 40));

        btnRegistrar.setBackground(new java.awt.Color(153, 153, 255));
        btnRegistrar.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setLabel("Registrar sesión de swimming");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 280, 60));

        lblPasos.setFont(new java.awt.Font("Arial Nova Light", 0, 21)); // NOI18N
        lblPasos.setForeground(new java.awt.Color(255, 255, 255));
        lblPasos.setText("Número de largos:");
        getContentPane().add(lblPasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, 40));

        spinnerFCMin.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        spinnerFCMin.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(spinnerFCMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 310, 40));

        spinnerDistancia.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        spinnerDistancia.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));
        getContentPane().add(spinnerDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 230, 40));

        lblActividad.setFont(new java.awt.Font("Arial Nova Light", 0, 36)); // NOI18N
        lblActividad.setForeground(new java.awt.Color(255, 255, 255));
        lblActividad.setText("Estás registrando una sesión de swimming");
        getContentPane().add(lblActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, 50));

        lblFCMin.setFont(new java.awt.Font("Arial Nova Light", 0, 19)); // NOI18N
        lblFCMin.setForeground(new java.awt.Color(255, 255, 255));
        lblFCMin.setText("Frecuencia cardíaca mínima (ppm):");
        getContentPane().add(lblFCMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, 40));

        lblInicio.setFont(new java.awt.Font("Arial Nova Light", 0, 21)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblInicio.setText("Fecha y hora de inicio:");
        getContentPane().add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 40));

        spinnerInicio.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        spinnerInicio.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_YEAR));
        getContentPane().add(spinnerInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 300, 40));

        lblElevacion.setFont(new java.awt.Font("Arial Nova Light", 0, 21)); // NOI18N
        lblElevacion.setForeground(new java.awt.Color(255, 255, 255));
        lblElevacion.setText("Tipo natación:");
        getContentPane().add(lblElevacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, 40));

        spinnerLargos.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        spinnerLargos.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));
        getContentPane().add(spinnerLargos, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 220, 40));

        lblFinal.setFont(new java.awt.Font("Arial Nova Light", 0, 21)); // NOI18N
        lblFinal.setForeground(new java.awt.Color(255, 255, 255));
        lblFinal.setText("Fecha y hora de final:");
        getContentPane().add(lblFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, 40));

        spinnerFinal.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        spinnerFinal.setModel(new javax.swing.SpinnerDateModel());
        getContentPane().add(spinnerFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 310, 40));

        cboxTipo.setFont(new java.awt.Font("Arial Nova Light", 0, 18)); // NOI18N
        cboxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Piscina", "Mar" }));
        getContentPane().add(cboxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 140, 40));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/infitnityFondo.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        //Recoger inputs
        Date dateInicio = (Date) spinnerInicio.getValue();
        fhInicio = dateInicio.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
        Date dateFin = (Date) spinnerFinal.getValue();
        fhFin = dateFin.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
        distancia = (float) spinnerDistancia.getValue();
        fcMax = (int) spinnerFCMax.getValue();
        fcMin = (int) spinnerFCMin.getValue();
        numLargos = ((Number)spinnerLargos.getValue()).intValue();
        tipo = cboxTipo.getSelectedIndex();
       
        //Comprobar que los datos introducidos son válidos
        if (Swimming.actividadValida(fhInicio, fhFin, distancia, fcMin, fcMax, numLargos)){ 
            
            // Crear actividad
            Swimming swimming = new Swimming(fhInicio, fhFin, distancia, fcMax, fcMin, numLargos, tipo); 
            
            //Mostrar mensaje de actividad creada con éxito
            JOptionPane.showMessageDialog(null, "Actividad creada con éxito.", "", JOptionPane.INFORMATION_MESSAGE);
            
            //Añadir actividad al historial del usuario
            usuario.getHistorialActividades().add(swimming);
            
            //Serializar
            UsuariosManager manager = UsuariosManager.getInstance();
            manager.guardarUsuarios();
            
            //Volver al menú principal
            MenuPrincipal menu = new MenuPrincipal();
            menu.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SwimmingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SwimmingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SwimmingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SwimmingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cboxTipo;
    private javax.swing.JLabel lblActividad;
    private javax.swing.JLabel lblDistancia;
    private javax.swing.JLabel lblElevacion;
    private javax.swing.JLabel lblFCMax;
    private javax.swing.JLabel lblFCMin;
    private javax.swing.JLabel lblFinal;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblPasos;
    private javax.swing.JSpinner spinnerDistancia;
    private javax.swing.JSpinner spinnerFCMax;
    private javax.swing.JSpinner spinnerFCMin;
    private javax.swing.JSpinner spinnerFinal;
    private javax.swing.JSpinner spinnerInicio;
    private javax.swing.JSpinner spinnerLargos;
    // End of variables declaration//GEN-END:variables
}
